# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63onfig_manager.proto\"-\n\rConfiguration\x12\x0c\n\x04\x62loc\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\"#\n\x12\x43onfigurationValue\x12\r\n\x05value\x18\x01 \x01(\t\"?\n\x10\x43onfigurationSet\x12\x0c\n\x04\x62loc\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x07\n\x05\x45MPTY2t\n\x14\x43onfigurationService\x12\x32\n\tGetConfig\x12\x0e.Configuration\x1a\x13.ConfigurationValue\"\x00\x12(\n\tSetConfig\x12\x11.ConfigurationSet\x1a\x06.EMPTY\"\x00\x62\x06proto3')



_CONFIGURATION = DESCRIPTOR.message_types_by_name['Configuration']
_CONFIGURATIONVALUE = DESCRIPTOR.message_types_by_name['ConfigurationValue']
_CONFIGURATIONSET = DESCRIPTOR.message_types_by_name['ConfigurationSet']
_EMPTY = DESCRIPTOR.message_types_by_name['EMPTY']
Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATION,
  '__module__' : 'config_manager_pb2'
  # @@protoc_insertion_point(class_scope:Configuration)
  })
_sym_db.RegisterMessage(Configuration)

ConfigurationValue = _reflection.GeneratedProtocolMessageType('ConfigurationValue', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONVALUE,
  '__module__' : 'config_manager_pb2'
  # @@protoc_insertion_point(class_scope:ConfigurationValue)
  })
_sym_db.RegisterMessage(ConfigurationValue)

ConfigurationSet = _reflection.GeneratedProtocolMessageType('ConfigurationSet', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONSET,
  '__module__' : 'config_manager_pb2'
  # @@protoc_insertion_point(class_scope:ConfigurationSet)
  })
_sym_db.RegisterMessage(ConfigurationSet)

EMPTY = _reflection.GeneratedProtocolMessageType('EMPTY', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'config_manager_pb2'
  # @@protoc_insertion_point(class_scope:EMPTY)
  })
_sym_db.RegisterMessage(EMPTY)

_CONFIGURATIONSERVICE = DESCRIPTOR.services_by_name['ConfigurationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIGURATION._serialized_start=24
  _CONFIGURATION._serialized_end=69
  _CONFIGURATIONVALUE._serialized_start=71
  _CONFIGURATIONVALUE._serialized_end=106
  _CONFIGURATIONSET._serialized_start=108
  _CONFIGURATIONSET._serialized_end=171
  _EMPTY._serialized_start=173
  _EMPTY._serialized_end=180
  _CONFIGURATIONSERVICE._serialized_start=182
  _CONFIGURATIONSERVICE._serialized_end=298
# @@protoc_insertion_point(module_scope)